### PR TITLE
Provide ability to control the HttpClientParams in the ZestBasicRunner

### PR DESCRIPTION
**Pull request by denniskniep**

### CODE REVIEW

**Comment by denniskniep** [comment]
I am especially interested to set the Parameter `HttpClientParams.ALLOW_CIRCULAR_REDIRECTS` in a Zap-Zest-Script to true. Because the HttpClient does not recognize if the Url has a new parameter after the redirect.
Requesting `foo.com`
Response redirects to `foo.com?id=5`
throws a `CircularRedirectException`

**Comment by thc202** [comment]
Which script type? (Sequence?) The Zest scripts in ZAP should be using the `HttpSender` class, which already has that enabled by default.

**Comment by denniskniep** [comment]
Yes Sequence.
I thought that the `ZestZapRunner` do this job. And this class inherits from `ZestBasicRunner` which defines his own `HttpClient` without this option set. Zap gets the Http-Calls because `ZestZapRunner` register Zap as proxy via the the `setProxy`.

**Comment by thc202** [comment]
Yeah, that might be better for the "generic" runners, some of them should not be proxying through ZAP though, but send the requests directly (which is more appropriate for the behaviour expected by the ZAP components e.g. Active Scanner showing the requests in the Active Scan tab).

**Pull request merged**
